"""Provider-neutral search, evidence-acquisition, and verification boundaries."""

from .contracts import (
    CandidateSourceType,
    SearchCapability,
    SearchProviderCapabilities,
    SearchQueryFamily,
    SearchRequest,
    SearchResponse,
    SearchResult,
    metadata_contains_secret_key,
)
from .engine import (
    EvidenceAssessment,
    EvidenceAssessor,
    EvidenceCollectionResult,
    EvidenceEngine,
    EvidenceRelation,
    ResearchCandidate,
    ResearchCollection,
    ResearchCollectionTask,
    ResearchPlan,
    ResearchQueryFailure,
    ResearchQuerySpec,
    ResearchRequestResult,
    ResearchTargetRole,
    SearchProviderSelector,
)
from .fact_check import (
    ClaimVerificationResult,
    FactCheckBatchResult,
    FactCheckEngine,
    FactCheckInvariants,
    FactCheckPolicy,
    FactCheckPolicyLoader,
    FactCheckThreshold,
    StoryVerificationResult,
)
from .policy import (
    SearchBudgets,
    SearchExecutionConstraints,
    SearchPolicy,
    SearchPolicyEnforcer,
    SearchPolicyLoader,
    SearchRules,
)
from .provider import (
    SearchCapabilityError,
    SearchInvalidResponseError,
    SearchProvider,
    SearchProviderError,
    SearchProviderPolicyError,
    SearchProviderRateLimitError,
    SearchProviderTimeoutError,
    SearchProviderUnavailableError,
    require_provider_compatibility,
)
from .registry import SearchProviderNotRegisteredError, SearchProviderRegistry

__all__ = [
    "CandidateSourceType",
    "ClaimVerificationResult",
    "EvidenceAssessment",
    "EvidenceAssessor",
    "EvidenceCollectionResult",
    "EvidenceEngine",
    "EvidenceRelation",
    "FactCheckBatchResult",
    "FactCheckEngine",
    "FactCheckInvariants",
    "FactCheckPolicy",
    "FactCheckPolicyLoader",
    "FactCheckThreshold",
    "ResearchCandidate",
    "ResearchCollection",
    "ResearchCollectionTask",
    "ResearchPlan",
    "ResearchQueryFailure",
    "ResearchQuerySpec",
    "ResearchRequestResult",
    "ResearchTargetRole",
    "SearchBudgets",
    "SearchCapability",
    "SearchCapabilityError",
    "SearchExecutionConstraints",
    "SearchInvalidResponseError",
    "SearchPolicy",
    "SearchPolicyEnforcer",
    "SearchPolicyLoader",
    "SearchProvider",
    "SearchProviderCapabilities",
    "SearchProviderError",
    "SearchProviderNotRegisteredError",
    "SearchProviderPolicyError",
    "SearchProviderRateLimitError",
    "SearchProviderRegistry",
    "SearchProviderSelector",
    "SearchProviderTimeoutError",
    "SearchProviderUnavailableError",
    "SearchQueryFamily",
    "SearchRequest",
    "SearchResponse",
    "SearchResult",
    "SearchRules",
    "StoryVerificationResult",
    "metadata_contains_secret_key",
    "require_provider_compatibility",
]
