#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'

# News AI Social Media Manager - portable local developer/test bootstrap.
#
# Supported entry environments:
#   - Linux distributions with a supported package/service manager
#   - macOS
#   - Windows through Git Bash/MSYS2/Cygwin
#   - WSL (handled as Linux; Docker Desktop integration is used when already available)
#
# The script creates an isolated PostgreSQL 16 + Redis 7 test environment,
# configures Docker/container restart persistence, writes .env.test.local,
# installs the project into .venv, and validates database connectivity/migrations.
#
# It never enables live Groq or live social publishing.

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$SCRIPT_DIR"
VENV_DIR="$REPO_ROOT/.venv"
ENV_FILE="$REPO_ROOT/.env.test.local"
STATE_FILE="$REPO_ROOT/.env.setup.state"

POSTGRES_CONTAINER="${NEWS_AI_TEST_POSTGRES_CONTAINER:-news-ai-test-postgres}"
REDIS_CONTAINER="${NEWS_AI_TEST_REDIS_CONTAINER:-news-ai-test-redis}"
POSTGRES_IMAGE="${NEWS_AI_TEST_POSTGRES_IMAGE:-postgres:16-alpine}"
REDIS_IMAGE="${NEWS_AI_TEST_REDIS_IMAGE:-redis:7-alpine}"

POSTGRES_DB="${NEWS_AI_TEST_POSTGRES_DB:-news_ai}"
POSTGRES_USER="${NEWS_AI_TEST_POSTGRES_USER:-postgres}"
POSTGRES_PASSWORD="${NEWS_AI_TEST_POSTGRES_PASSWORD:-postgres}"

DOCKER_CMD=()
PYTHON_BIN=""
VENV_PYTHON=""
PLATFORM=""
LINUX_ID=""
LINUX_ID_LIKE=""
IS_WSL=0

# Persistent setup ownership. Values are written to the git-ignored state file so
# clean.sh can undo only host changes that this setup introduced.
STATE_DOCKER_INSTALLED_BY_SETUP="${STATE_DOCKER_INSTALLED_BY_SETUP:-0}"
STATE_DOCKER_INSTALL_METHOD="${STATE_DOCKER_INSTALL_METHOD:-none}"
STATE_DOCKER_PACKAGE="${STATE_DOCKER_PACKAGE:-none}"
STATE_DOCKER_AUTOSTART_BY_SETUP="${STATE_DOCKER_AUTOSTART_BY_SETUP:-0}"
STATE_DOCKER_STARTED_BY_SETUP="${STATE_DOCKER_STARTED_BY_SETUP:-0}"
STATE_DOCKER_AUTOSTART_KIND="${STATE_DOCKER_AUTOSTART_KIND:-none}"
STATE_DESKTOP_AUTOSTART_PATH="${STATE_DESKTOP_AUTOSTART_PATH:-}"
STATE_POSTGRES_IMAGE_PRESENT_BEFORE="${STATE_POSTGRES_IMAGE_PRESENT_BEFORE:-unknown}"
STATE_REDIS_IMAGE_PRESENT_BEFORE="${STATE_REDIS_IMAGE_PRESENT_BEFORE:-unknown}"
STATE_VENV_SUPPORT_INSTALLED_BY_SETUP="${STATE_VENV_SUPPORT_INSTALLED_BY_SETUP:-0}"
STATE_VENV_SUPPORT_METHOD="${STATE_VENV_SUPPORT_METHOD:-none}"
STATE_VENV_SUPPORT_PACKAGE="${STATE_VENV_SUPPORT_PACKAGE:-none}"

log() {
  printf '\n==> %s\n' "$*"
}

warn() {
  printf '\nWARNING: %s\n' "$*" >&2
}

die() {
  printf '\nERROR: %s\n' "$*" >&2
  exit 1
}

have() {
  command -v "$1" >/dev/null 2>&1
}

run_as_root() {
  if [[ "${EUID:-$(id -u)}" -eq 0 ]]; then
    "$@"
  elif have sudo; then
    sudo "$@"
  else
    die "This step requires root privileges, but sudo is not installed."
  fi
}

run_docker() {
  "${DOCKER_CMD[@]}" "$@"
}

require_repo_root() {
  [[ -f "$REPO_ROOT/pyproject.toml" ]] \
    || die "setup.sh must live in the repository root next to pyproject.toml."
  cd "$REPO_ROOT"
}

detect_platform() {
  local uname_s
  uname_s="$(uname -s 2>/dev/null || true)"
  case "$uname_s" in
    Linux)
      PLATFORM="linux"
      if grep -qi microsoft /proc/version 2>/dev/null; then
        IS_WSL=1
      fi
      if [[ -r /etc/os-release ]]; then
        # shellcheck disable=SC1091
        source /etc/os-release
        LINUX_ID="${ID:-unknown}"
        LINUX_ID_LIKE="${ID_LIKE:-}"
      fi
      ;;
    Darwin)
      PLATFORM="macos"
      ;;
    MINGW*|MSYS*|CYGWIN*)
      PLATFORM="windows"
      ;;
    *)
      die "Unsupported host '$uname_s'. Use Linux, macOS, Windows Git Bash/MSYS2/Cygwin, or WSL."
      ;;
  esac

  if [[ "$IS_WSL" == "1" ]]; then
    log "Detected WSL on ${LINUX_ID:-Linux}"
  else
    log "Detected platform: $PLATFORM${LINUX_ID:+ ($LINUX_ID)}"
  fi
}

save_state() {
  umask 077
  {
    printf '# Generated by setup.sh. Used only by clean.sh.\n'
    printf 'STATE_DOCKER_INSTALLED_BY_SETUP=%q\n' "$STATE_DOCKER_INSTALLED_BY_SETUP"
    printf 'STATE_DOCKER_INSTALL_METHOD=%q\n' "$STATE_DOCKER_INSTALL_METHOD"
    printf 'STATE_DOCKER_PACKAGE=%q\n' "$STATE_DOCKER_PACKAGE"
    printf 'STATE_DOCKER_AUTOSTART_BY_SETUP=%q\n' "$STATE_DOCKER_AUTOSTART_BY_SETUP"
    printf 'STATE_DOCKER_STARTED_BY_SETUP=%q\n' "$STATE_DOCKER_STARTED_BY_SETUP"
    printf 'STATE_DOCKER_AUTOSTART_KIND=%q\n' "$STATE_DOCKER_AUTOSTART_KIND"
    printf 'STATE_DESKTOP_AUTOSTART_PATH=%q\n' "$STATE_DESKTOP_AUTOSTART_PATH"
    printf 'STATE_POSTGRES_IMAGE_PRESENT_BEFORE=%q\n' "$STATE_POSTGRES_IMAGE_PRESENT_BEFORE"
    printf 'STATE_REDIS_IMAGE_PRESENT_BEFORE=%q\n' "$STATE_REDIS_IMAGE_PRESENT_BEFORE"
    printf 'STATE_VENV_SUPPORT_INSTALLED_BY_SETUP=%q\n' "$STATE_VENV_SUPPORT_INSTALLED_BY_SETUP"
    printf 'STATE_VENV_SUPPORT_METHOD=%q\n' "$STATE_VENV_SUPPORT_METHOD"
    printf 'STATE_VENV_SUPPORT_PACKAGE=%q\n' "$STATE_VENV_SUPPORT_PACKAGE"
  } > "$STATE_FILE"
  chmod 600 "$STATE_FILE" 2>/dev/null || true
}

load_state() {
  if [[ -f "$STATE_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$STATE_FILE"
  fi
  save_state
}

find_python() {
  local candidates=()
  local candidate

  if [[ -n "${PYTHON_BIN_OVERRIDE:-}" ]]; then
    candidates+=("$PYTHON_BIN_OVERRIDE")
  fi

  if [[ "$PLATFORM" == "windows" ]]; then
    candidates+=(python.exe python3.exe python)
  else
    candidates+=(python3.14 python3.13 python3.12 python3.11 python3 python)
  fi

  for candidate in "${candidates[@]}"; do
    if have "$candidate" && "$candidate" -c \
      'import sys; raise SystemExit(0 if sys.version_info >= (3, 11) else 1)' \
      >/dev/null 2>&1; then
      PYTHON_BIN="$(command -v "$candidate")"
      break
    fi
  done

  [[ -n "$PYTHON_BIN" ]] || die \
    "Python >= 3.11 is required. Install Python 3.11+ for this host and rerun setup.sh."

  log "Using Python: $("$PYTHON_BIN" --version 2>&1) ($PYTHON_BIN)"
}

resolve_venv_python() {
  if [[ -x "$VENV_DIR/bin/python" ]]; then
    VENV_PYTHON="$VENV_DIR/bin/python"
  elif [[ -x "$VENV_DIR/Scripts/python.exe" ]]; then
    VENV_PYTHON="$VENV_DIR/Scripts/python.exe"
  elif [[ -x "$VENV_DIR/Scripts/python" ]]; then
    VENV_PYTHON="$VENV_DIR/Scripts/python"
  else
    return 1
  fi
}

install_venv_support_linux() {
  if have apt-get; then
    run_as_root apt-get update
    run_as_root apt-get install -y python3-venv
    STATE_VENV_SUPPORT_INSTALLED_BY_SETUP=1
    STATE_VENV_SUPPORT_METHOD=apt
    STATE_VENV_SUPPORT_PACKAGE=python3-venv
  elif have apk; then
    run_as_root apk add py3-virtualenv
    STATE_VENV_SUPPORT_INSTALLED_BY_SETUP=1
    STATE_VENV_SUPPORT_METHOD=apk
    STATE_VENV_SUPPORT_PACKAGE=py3-virtualenv
  elif have dnf; then
    run_as_root dnf install -y python3-pip
    STATE_VENV_SUPPORT_INSTALLED_BY_SETUP=1
    STATE_VENV_SUPPORT_METHOD=dnf
    STATE_VENV_SUPPORT_PACKAGE=python3-pip
  elif have yum; then
    run_as_root yum install -y python3-pip
    STATE_VENV_SUPPORT_INSTALLED_BY_SETUP=1
    STATE_VENV_SUPPORT_METHOD=yum
    STATE_VENV_SUPPORT_PACKAGE=python3-pip
  elif have pacman; then
    run_as_root pacman -S --needed --noconfirm python-virtualenv
    STATE_VENV_SUPPORT_INSTALLED_BY_SETUP=1
    STATE_VENV_SUPPORT_METHOD=pacman
    STATE_VENV_SUPPORT_PACKAGE=python-virtualenv
  elif have zypper; then
    run_as_root zypper --non-interactive install python3-pip
    STATE_VENV_SUPPORT_INSTALLED_BY_SETUP=1
    STATE_VENV_SUPPORT_METHOD=zypper
    STATE_VENV_SUPPORT_PACKAGE=python3-pip
  elif have xbps-install; then
    run_as_root xbps-install -Sy python3-pip
    STATE_VENV_SUPPORT_INSTALLED_BY_SETUP=1
    STATE_VENV_SUPPORT_METHOD=xbps
    STATE_VENV_SUPPORT_PACKAGE=python3-pip
  else
    return 1
  fi
  save_state
}

ensure_venv() {
  local recreate=0

  if resolve_venv_python; then
    if ! "$VENV_PYTHON" -c \
      'import sys; raise SystemExit(0 if sys.version_info >= (3, 11) else 1)' \
      >/dev/null 2>&1; then
      warn "Existing .venv is broken or uses unsupported Python; recreating it."
      recreate=1
    fi
  else
    recreate=1
  fi

  if [[ "$recreate" -eq 1 ]]; then
    rm -rf "$VENV_DIR"
    log "Creating virtual environment"
    if ! "$PYTHON_BIN" -m venv "$VENV_DIR"; then
      if [[ "$PLATFORM" == "linux" ]] && install_venv_support_linux; then
        if ! "$PYTHON_BIN" -m venv "$VENV_DIR"; then
          have virtualenv && virtualenv -p "$PYTHON_BIN" "$VENV_DIR" \
            || "$PYTHON_BIN" -m virtualenv "$VENV_DIR"
        fi
      else
        die "Unable to create .venv with $PYTHON_BIN."
      fi
    fi
    resolve_venv_python || die "Virtual environment was created but its Python executable is missing."
  else
    log "Reusing existing virtual environment"
  fi

  log "Installing project and development dependencies"
  "$VENV_PYTHON" -m pip install -e '.[dev]'
}

install_docker_linux() {
  log "Docker was not found; installing it for this Linux host"

  if have apt-get; then
    run_as_root apt-get update
    run_as_root apt-get install -y docker.io
    STATE_DOCKER_INSTALL_METHOD=apt
    STATE_DOCKER_PACKAGE=docker.io
  elif have apk; then
    run_as_root apk add docker
    STATE_DOCKER_INSTALL_METHOD=apk
    STATE_DOCKER_PACKAGE=docker
  elif have dnf; then
    if run_as_root dnf install -y moby-engine; then
      STATE_DOCKER_PACKAGE=moby-engine
    else
      run_as_root dnf install -y docker
      STATE_DOCKER_PACKAGE=docker
    fi
    STATE_DOCKER_INSTALL_METHOD=dnf
  elif have yum; then
    if run_as_root yum install -y moby-engine; then
      STATE_DOCKER_PACKAGE=moby-engine
    else
      run_as_root yum install -y docker
      STATE_DOCKER_PACKAGE=docker
    fi
    STATE_DOCKER_INSTALL_METHOD=yum
  elif have pacman; then
    run_as_root pacman -S --needed --noconfirm docker
    STATE_DOCKER_INSTALL_METHOD=pacman
    STATE_DOCKER_PACKAGE=docker
  elif have zypper; then
    run_as_root zypper --non-interactive install docker
    STATE_DOCKER_INSTALL_METHOD=zypper
    STATE_DOCKER_PACKAGE=docker
  elif have xbps-install; then
    run_as_root xbps-install -Sy docker
    STATE_DOCKER_INSTALL_METHOD=xbps
    STATE_DOCKER_PACKAGE=docker
  elif have eopkg; then
    run_as_root eopkg install -y docker
    STATE_DOCKER_INSTALL_METHOD=eopkg
    STATE_DOCKER_PACKAGE=docker
  elif have swupd; then
    run_as_root swupd bundle-add containers-basic
    STATE_DOCKER_INSTALL_METHOD=swupd
    STATE_DOCKER_PACKAGE=containers-basic
  elif have emerge; then
    run_as_root emerge --noreplace app-containers/docker
    STATE_DOCKER_INSTALL_METHOD=emerge
    STATE_DOCKER_PACKAGE=app-containers/docker
  else
    die "Docker is missing and no supported package manager was detected. Install Docker Engine for this Linux host and rerun setup.sh."
  fi

  STATE_DOCKER_INSTALLED_BY_SETUP=1
  save_state
}

install_docker_macos() {
  log "Docker was not found; installing Docker Desktop for macOS"
  if have brew; then
    brew install --cask docker
    STATE_DOCKER_INSTALL_METHOD=brew-cask
    STATE_DOCKER_PACKAGE=docker
  else
    local arch url tmpdir
    arch="$(uname -m)"
    case "$arch" in
      arm64|aarch64) arch=arm64 ;;
      *) arch=amd64 ;;
    esac
    url="https://desktop.docker.com/mac/main/${arch}/Docker.dmg"
    tmpdir="$(mktemp -d)"
    curl -fL "$url" -o "$tmpdir/Docker.dmg"
    hdiutil attach "$tmpdir/Docker.dmg" -nobrowse -quiet
    run_as_root ditto /Volumes/Docker/Docker.app /Applications/Docker.app
    hdiutil detach /Volumes/Docker -quiet || true
    rm -rf "$tmpdir"
    STATE_DOCKER_INSTALL_METHOD=mac-dmg
    STATE_DOCKER_PACKAGE=/Applications/Docker.app
  fi
  STATE_DOCKER_INSTALLED_BY_SETUP=1
  save_state
}

windows_program_files_unix() {
  local value="${PROGRAMFILES:-C:\\Program Files}"
  if have cygpath; then
    cygpath -u "$value"
  else
    printf '%s\n' "/c/Program Files"
  fi
}

windows_appdata_unix() {
  local value="${APPDATA:-}"
  [[ -n "$value" ]] || return 1
  if have cygpath; then
    cygpath -u "$value"
  else
    return 1
  fi
}

install_docker_windows() {
  log "Docker was not found; installing Docker Desktop for Windows"
  if have winget.exe; then
    winget.exe install --exact --id Docker.DockerDesktop \
      --accept-package-agreements --accept-source-agreements --silent
    STATE_DOCKER_INSTALL_METHOD=winget
    STATE_DOCKER_PACKAGE=Docker.DockerDesktop
  elif have choco.exe; then
    choco.exe install docker-desktop -y
    STATE_DOCKER_INSTALL_METHOD=choco
    STATE_DOCKER_PACKAGE=docker-desktop
  else
    have curl || die "Docker Desktop is missing and neither winget, Chocolatey, nor curl is available."
    local arch tmpdir installer installer_win
    arch="${PROCESSOR_ARCHITECTURE:-AMD64}"
    [[ "${arch^^}" == "ARM64" ]] && arch=arm64 || arch=amd64
    tmpdir="$(mktemp -d)"
    installer="$tmpdir/Docker Desktop Installer.exe"
    curl -fL "https://desktop.docker.com/win/main/${arch}/Docker%20Desktop%20Installer.exe" \
      -o "$installer"
    have cygpath || die "Direct Windows Docker installation requires cygpath (Git Bash/MSYS2/Cygwin)."
    installer_win="$(cygpath -w "$installer")"
    powershell.exe -NoProfile -Command \
      "Start-Process -FilePath '$installer_win' -ArgumentList 'install','--quiet','--accept-license' -Wait -Verb RunAs"
    rm -rf "$tmpdir"
    STATE_DOCKER_INSTALL_METHOD=windows-direct
    STATE_DOCKER_PACKAGE=Docker.DockerDesktop
  fi
  STATE_DOCKER_INSTALLED_BY_SETUP=1
  save_state
}

install_docker_if_missing() {
  if have docker || have docker.exe; then
    return
  fi

  case "$PLATFORM" in
    linux) install_docker_linux ;;
    macos) install_docker_macos ;;
    windows) install_docker_windows ;;
  esac
}

ensure_docker_cli_path() {
  if have docker || have docker.exe; then
    return
  fi

  if [[ "$PLATFORM" == "macos" && -x /Applications/Docker.app/Contents/Resources/bin/docker ]]; then
    PATH="/Applications/Docker.app/Contents/Resources/bin:$PATH"
    export PATH
  elif [[ "$PLATFORM" == "windows" ]]; then
    local pf
    pf="$(windows_program_files_unix)"
    if [[ -x "$pf/Docker/Docker/resources/bin/docker.exe" ]]; then
      PATH="$pf/Docker/Docker/resources/bin:$PATH"
      export PATH
    fi
  fi
}

configure_linux_docker_service() {
  if have systemctl; then
    if ! systemctl is-enabled docker >/dev/null 2>&1; then
      STATE_DOCKER_AUTOSTART_BY_SETUP=1
      STATE_DOCKER_AUTOSTART_KIND=systemd
      save_state
    fi
    run_as_root systemctl enable --now docker
  elif have rc-update && have rc-service; then
    if ! rc-update show default 2>/dev/null | grep -qE '(^|[[:space:]])docker([[:space:]]|$)'; then
      STATE_DOCKER_AUTOSTART_BY_SETUP=1
      STATE_DOCKER_AUTOSTART_KIND=openrc
      save_state
    fi
    run_as_root rc-update add docker default
    run_as_root rc-service docker start
  elif have sv && [[ -d /etc/sv/docker ]]; then
    if [[ ! -e /var/service/docker ]]; then
      STATE_DOCKER_AUTOSTART_BY_SETUP=1
      STATE_DOCKER_AUTOSTART_KIND=runit
      save_state
      run_as_root ln -s /etc/sv/docker /var/service/docker
    fi
    run_as_root sv up docker
  elif have chkconfig && have service; then
    if ! chkconfig --list docker 2>/dev/null | grep -qE '3:on|5:on'; then
      STATE_DOCKER_AUTOSTART_BY_SETUP=1
      STATE_DOCKER_AUTOSTART_KIND=sysv
      save_state
    fi
    run_as_root chkconfig docker on
    run_as_root service docker start
  elif have update-rc.d && have service; then
    STATE_DOCKER_AUTOSTART_BY_SETUP=1
    STATE_DOCKER_AUTOSTART_KIND=sysv
    save_state
    run_as_root update-rc.d docker defaults
    run_as_root service docker start
  elif have service; then
    die "Docker is installed, but this Linux host has no recognized command to enable Docker at boot."
  else
    die "Docker is installed but no supported service manager was found to start and boot-enable it."
  fi
}

find_macos_docker_desktop() {
  [[ -d /Applications/Docker.app ]] && {
    printf '%s\n' /Applications/Docker.app
    return 0
  }
  [[ -d "$HOME/Applications/Docker.app" ]] && {
    printf '%s\n' "$HOME/Applications/Docker.app"
    return 0
  }
  return 1
}

configure_macos_docker_desktop() {
  local app plist
  app="$(find_macos_docker_desktop)" || die "Docker Desktop was installed but Docker.app was not found."
  open "$app" >/dev/null 2>&1 || open -a Docker >/dev/null 2>&1 || true

  plist="$HOME/Library/LaunchAgents/in.quotely.news-ai-docker.plist"
  if [[ ! -f "$plist" ]]; then
    mkdir -p "$(dirname "$plist")"
    cat > "$plist" <<'EOF_PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>in.quotely.news-ai-docker</string>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/bin/open</string>
    <string>-a</string>
    <string>Docker</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
</dict>
</plist>
EOF_PLIST
    launchctl load "$plist" >/dev/null 2>&1 || true
    STATE_DOCKER_AUTOSTART_BY_SETUP=1
    STATE_DOCKER_AUTOSTART_KIND=launchd
    STATE_DESKTOP_AUTOSTART_PATH="$plist"
    save_state
  fi
}

find_windows_docker_desktop() {
  local pf
  pf="$(windows_program_files_unix)"
  [[ -x "$pf/Docker/Docker/Docker Desktop.exe" ]] && {
    printf '%s\n' "$pf/Docker/Docker/Docker Desktop.exe"
    return 0
  }
  return 1
}

configure_windows_docker_desktop() {
  local app appdata startup_dir startup_file app_win
  app="$(find_windows_docker_desktop)" || die "Docker Desktop was installed but its executable was not found."
  "$app" >/dev/null 2>&1 &

  appdata="$(windows_appdata_unix || true)"
  if [[ -n "$appdata" ]]; then
    startup_dir="$appdata/Microsoft/Windows/Start Menu/Programs/Startup"
    startup_file="$startup_dir/NewsAILocalDockerDesktop.cmd"
    if [[ ! -f "$startup_file" ]]; then
      mkdir -p "$startup_dir"
      app_win="$(cygpath -w "$app")"
      printf '@echo off\r\nstart "" "%s"\r\n' "$app_win" > "$startup_file"
      STATE_DOCKER_AUTOSTART_BY_SETUP=1
      STATE_DOCKER_AUTOSTART_KIND=windows-startup
      STATE_DESKTOP_AUTOSTART_PATH="$startup_file"
      save_state
    fi
  else
    die "Could not locate the Windows Startup folder to make Docker Desktop restart-safe."
  fi
}

configure_wsl_docker_desktop_autostart() {
  have powershell.exe || die "WSL is using an external Docker engine, but Windows interop is unavailable to configure Docker Desktop startup."
  have wslpath || die "WSL is missing wslpath, so Docker Desktop startup cannot be configured."

  local startup_win startup_dir startup_file docker_app_win
  startup_win="$(powershell.exe -NoProfile -Command '[Environment]::GetFolderPath("Startup")' 2>/dev/null | tr -d '\r')"
  [[ -n "$startup_win" ]] || die "Could not resolve the Windows Startup folder from WSL."
  startup_dir="$(wslpath -u "$startup_win")"
  startup_file="$startup_dir/NewsAILocalDockerDesktop.cmd"
  docker_app_win='C:\Program Files\Docker\Docker\Docker Desktop.exe'

  if [[ ! -f "$startup_file" ]]; then
    mkdir -p "$startup_dir"
    printf '@echo off\r\nstart "" "%s"\r\n' "$docker_app_win" > "$startup_file"
    STATE_DOCKER_AUTOSTART_BY_SETUP=1
    STATE_DOCKER_AUTOSTART_KIND=windows-startup-wsl
    STATE_DESKTOP_AUTOSTART_PATH="$startup_file"
    save_state
  fi
}

docker_engine_reachable() {
  if have docker && docker info >/dev/null 2>&1; then
    return 0
  fi
  if have docker.exe && docker.exe info >/dev/null 2>&1; then
    return 0
  fi
  if [[ "$PLATFORM" == "linux" ]] && have sudo && sudo docker info >/dev/null 2>&1; then
    return 0
  fi
  return 1
}

configure_docker_startup() {
  if ! docker_engine_reachable && [[ "$STATE_DOCKER_STARTED_BY_SETUP" != "1" ]]; then
    STATE_DOCKER_STARTED_BY_SETUP=1
    save_state
  fi
  if [[ "$PLATFORM" == "linux" && "$IS_WSL" == "1" ]]; then
    if (have docker && docker info >/dev/null 2>&1) \
      || (have docker.exe && docker.exe info >/dev/null 2>&1); then
      log "Using the Docker engine exposed to WSL; configuring Docker Desktop startup."
      configure_wsl_docker_desktop_autostart
      return
    fi
  fi

  case "$PLATFORM" in
    linux) configure_linux_docker_service ;;
    macos) configure_macos_docker_desktop ;;
    windows) configure_windows_docker_desktop ;;
  esac
}

select_docker_command() {
  ensure_docker_cli_path

  if have docker && docker info >/dev/null 2>&1; then
    DOCKER_CMD=(docker)
    return
  fi
  if have docker.exe && docker.exe info >/dev/null 2>&1; then
    DOCKER_CMD=(docker.exe)
    return
  fi

  if [[ "$PLATFORM" == "linux" ]] && have sudo && sudo docker info >/dev/null 2>&1; then
    DOCKER_CMD=(sudo docker)
    warn "Docker requires sudo for this user. setup.sh will use sudo docker and will not change docker-group membership."
    return
  fi

  die "Docker is installed but its engine is not reachable."
}

wait_for_docker() {
  local attempt
  ensure_docker_cli_path
  for ((attempt = 1; attempt <= 120; attempt++)); do
    if have docker && docker info >/dev/null 2>&1; then
      return 0
    fi
    if have docker.exe && docker.exe info >/dev/null 2>&1; then
      return 0
    fi
    if [[ "$PLATFORM" == "linux" ]] && have sudo && sudo docker info >/dev/null 2>&1; then
      return 0
    fi
    sleep 1
  done
  die "Timed out waiting for the Docker engine to become ready."
}

container_owned_or_absent() {
  local name="$1"
  if ! run_docker container inspect "$name" >/dev/null 2>&1; then
    return 0
  fi
  local label
  label="$(run_docker inspect -f '{{index .Config.Labels "news-ai.local-test"}}' "$name" 2>/dev/null || true)"
  [[ "$label" == "true" ]] || die \
    "Container '$name' already exists without the news-ai.local-test ownership label; refusing to delete it."
}

wait_for_healthy() {
  local container="$1"
  local max_attempts="${2:-60}"
  local status=""
  local attempt

  for ((attempt = 1; attempt <= max_attempts; attempt++)); do
    status="$(run_docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "$container" 2>/dev/null || true)"
    case "$status" in
      healthy)
        return 0
        ;;
      unhealthy|exited|dead)
        run_docker logs --tail 100 "$container" >&2 || true
        die "$container entered state '$status'."
        ;;
    esac
    sleep 1
  done

  run_docker logs --tail 100 "$container" >&2 || true
  die "Timed out waiting for $container to become healthy."
}

remember_image_state() {
  if [[ "$STATE_POSTGRES_IMAGE_PRESENT_BEFORE" == "unknown" ]]; then
    if run_docker image inspect "$POSTGRES_IMAGE" >/dev/null 2>&1; then
      STATE_POSTGRES_IMAGE_PRESENT_BEFORE=1
    else
      STATE_POSTGRES_IMAGE_PRESENT_BEFORE=0
    fi
  fi
  if [[ "$STATE_REDIS_IMAGE_PRESENT_BEFORE" == "unknown" ]]; then
    if run_docker image inspect "$REDIS_IMAGE" >/dev/null 2>&1; then
      STATE_REDIS_IMAGE_PRESENT_BEFORE=1
    else
      STATE_REDIS_IMAGE_PRESENT_BEFORE=0
    fi
  fi
  save_state
}

start_test_services() {
  container_owned_or_absent "$POSTGRES_CONTAINER"
  container_owned_or_absent "$REDIS_CONTAINER"
  remember_image_state

  log "Pulling CI-matching PostgreSQL and Redis images"
  run_docker pull "$POSTGRES_IMAGE"
  run_docker pull "$REDIS_IMAGE"

  log "Recreating isolated restartable test containers"
  run_docker rm -fv "$POSTGRES_CONTAINER" "$REDIS_CONTAINER" >/dev/null 2>&1 || true

  run_docker run -d \
    --name "$POSTGRES_CONTAINER" \
    --label news-ai.local-test=true \
    --restart unless-stopped \
    -e "POSTGRES_DB=$POSTGRES_DB" \
    -e "POSTGRES_USER=$POSTGRES_USER" \
    -e "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" \
    -p 127.0.0.1::5432 \
    --health-cmd="pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" \
    --health-interval=2s \
    --health-timeout=5s \
    --health-retries=30 \
    "$POSTGRES_IMAGE" >/dev/null

  run_docker run -d \
    --name "$REDIS_CONTAINER" \
    --label news-ai.local-test=true \
    --restart unless-stopped \
    -p 127.0.0.1::6379 \
    --health-cmd="redis-cli ping" \
    --health-interval=2s \
    --health-timeout=5s \
    --health-retries=30 \
    "$REDIS_IMAGE" >/dev/null

  wait_for_healthy "$POSTGRES_CONTAINER"
  wait_for_healthy "$REDIS_CONTAINER"

  POSTGRES_PORT="$(run_docker port "$POSTGRES_CONTAINER" 5432/tcp | awk -F: 'NR == 1 {print $NF}')"
  REDIS_PORT="$(run_docker port "$REDIS_CONTAINER" 6379/tcp | awk -F: 'NR == 1 {print $NF}')"

  [[ "$POSTGRES_PORT" =~ ^[0-9]+$ ]] || die "Could not determine PostgreSQL host port."
  [[ "$REDIS_PORT" =~ ^[0-9]+$ ]] || die "Could not determine Redis host port."

  log "PostgreSQL is healthy on 127.0.0.1:$POSTGRES_PORT"
  log "Redis is healthy on 127.0.0.1:$REDIS_PORT"
}

config_dir_for_env() {
  if [[ "$PLATFORM" == "windows" ]] && have cygpath; then
    cygpath -w "$REPO_ROOT/config"
  else
    printf '%s\n' "$REPO_ROOT/config"
  fi
}

write_test_env() {
  local database_url redis_url config_dir
  database_url="postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@127.0.0.1:${POSTGRES_PORT}/${POSTGRES_DB}"
  redis_url="redis://127.0.0.1:${REDIS_PORT}/0"
  config_dir="$(config_dir_for_env)"

  log "Writing deterministic non-live test environment to $ENV_FILE"

  umask 077
  {
    printf '# Generated by setup.sh. Local testing only. Do not commit.\n'
    printf '# Source from Bash-compatible shells: source .env.test.local\n'
    printf '# Live Groq is deliberately disabled so the ordinary suite has exactly one skip.\n\n'
    printf 'export NEWS_AI_ENVIRONMENT=%q\n' "test"
    printf 'export NEWS_AI_CONFIG_DIR=%q\n' "$config_dir"
    printf 'export NEWS_AI_DATABASE_URL=%q\n' "$database_url"
    printf 'export NEWS_AI_REDIS_URL=%q\n' "$redis_url"
    printf 'export NEWS_AI_READINESS_TIMEOUT_SECONDS=%q\n' "5"
    printf 'export NEWS_AI_SOCIAL_MODE=%q\n' "MOCK"
    printf 'export NEWS_AI_PUBLISHING_ENABLED=%q\n' "false"
    printf 'unset NEWS_AI_PUBLISHING_PAUSED\n'
    printf 'export NEWS_AI_RUN_LIVE_GROQ=%q\n' "0"
    printf 'unset GROQ_API_KEY\n'
  } > "$ENV_FILE"

  chmod 600 "$ENV_FILE" 2>/dev/null || true

  if have git && git -C "$REPO_ROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    git -C "$REPO_ROOT" check-ignore -q "$ENV_FILE" \
      || die "$ENV_FILE is not ignored by Git; refusing to leave a local environment file."
  fi
}

verify_test_services() {
  # shellcheck disable=SC1090
  source "$ENV_FILE"

  log "Verifying generated PostgreSQL and Redis URLs"
  "$VENV_PYTHON" - <<'PY'
import os

from redis import Redis
from sqlalchemy import create_engine, text

engine = create_engine(os.environ["NEWS_AI_DATABASE_URL"], pool_pre_ping=True)
try:
    with engine.connect() as connection:
        assert connection.execute(text("SELECT 1")).scalar_one() == 1
finally:
    engine.dispose()

client = Redis.from_url(os.environ["NEWS_AI_REDIS_URL"])
try:
    assert client.ping() is True
finally:
    client.close()
PY
}

prepare_database() {
  # shellcheck disable=SC1090
  source "$ENV_FILE"

  log "Applying Alembic migrations to the disposable PostgreSQL database"
  "$VENV_PYTHON" -m alembic upgrade head

  log "Checking migration drift"
  "$VENV_PYTHON" -m alembic check
}

print_summary() {
  cat <<EOF_SUMMARY

===============================================================================
News AI local test setup is ready.

Python:
  $("$VENV_PYTHON" --version 2>&1)

Persistent test services:
  PostgreSQL: $POSTGRES_IMAGE -> 127.0.0.1:$POSTGRES_PORT
  Redis:      $REDIS_IMAGE -> 127.0.0.1:$REDIS_PORT
  Restart:    unless-stopped
  Live Groq:  disabled (the one intentional pytest skip)

For every new Bash-compatible shell:

  source .env.test.local
  source .venv/bin/activate   # Windows Git Bash: source .venv/Scripts/activate

Run the complete non-live test suite:

  python -m pytest

The expected skip is only:
  tests/integration/test_live_groq.py::test_live_groq_structured_completion_normalizes_without_reasoning

Clean this local setup:

  source ./clean.sh

Docker/container persistence is configured for this host. On Linux the Docker
service is boot-enabled when the detected init system supports it. On macOS and
Windows Docker Desktop is started at user login; the test containers then return
automatically because they use Docker's unless-stopped restart policy.
===============================================================================
EOF_SUMMARY
}

main() {
  require_repo_root
  detect_platform
  load_state
  find_python
  ensure_venv
  install_docker_if_missing
  ensure_docker_cli_path
  configure_docker_startup
  wait_for_docker
  select_docker_command
  start_test_services
  write_test_env
  verify_test_services
  prepare_database
  print_summary
}

main "$@"
