"""Enums defined by docs/CANONICAL_CONTRACTS.md."""

from enum import StrEnum


class ClaimVerificationStatus(StrEnum):
    UNASSESSED = "UNASSESSED"
    SUPPORTED = "SUPPORTED"
    PARTIALLY_SUPPORTED = "PARTIALLY_SUPPORTED"
    DISPUTED = "DISPUTED"
    UNVERIFIED = "UNVERIFIED"
    REFUTED = "REFUTED"


class FactCheckLabel(StrEnum):
    TRUE = "TRUE"
    MOSTLY_TRUE = "MOSTLY_TRUE"
    PARTIALLY_TRUE = "PARTIALLY_TRUE"
    MISLEADING = "MISLEADING"
    OUT_OF_CONTEXT = "OUT_OF_CONTEXT"
    UNVERIFIED = "UNVERIFIED"
    FALSE = "FALSE"
    FABRICATED = "FABRICATED"
    SATIRE = "SATIRE"


class RiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ReviewState(StrEnum):
    NOT_READY = "NOT_READY"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    IN_REVIEW = "IN_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"


class PublicationStatus(StrEnum):
    DRAFT = "DRAFT"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    APPROVED = "APPROVED"
    SCHEDULED = "SCHEDULED"
    PUBLISHING = "PUBLISHING"
    RETRYING = "RETRYING"
    BLOCKED = "BLOCKED"
    PUBLISHED = "PUBLISHED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
