"""Provider-neutral AI platform contracts, adapters, and routing."""

from .contracts import (
    AIRequest,
    AIResponse,
    AIResponseFormat,
    AITaskType,
    PromptReference,
    ProviderCapabilities,
    ProviderLocality,
    TokenUsage,
    metadata_contains_secret_key,
)
from .llama_cpp import LlamaCppProvider, LlamaCppProviderConfig
from .provider import (
    AICapabilityError,
    AIContextTooLargeError,
    AIInvalidResponseError,
    AILocalResourceExhaustedError,
    AIProvider,
    AIProviderError,
    AIProviderPolicyError,
    AIProviderRateLimitError,
    AIProviderTimeoutError,
    AIProviderUnavailableError,
    require_provider_compatibility,
)
from .registry import AIProviderNotRegisteredError, AIProviderRegistry
from .routing import (
    AIFailureReason,
    AIRouteAttempt,
    AIRouteAttemptOutcome,
    AIRoutedResponse,
    AIRouter,
    AIRoutingConfig,
    AIRoutingConfigLoader,
    AIRoutingError,
    AIRoutingExecutionError,
    AIRoutingMode,
    AIRoutingPolicyError,
    TaskRoutingPolicy,
)

__all__ = [
    "AICapabilityError",
    "AIContextTooLargeError",
    "AIFailureReason",
    "AIInvalidResponseError",
    "AILocalResourceExhaustedError",
    "AIProvider",
    "AIProviderError",
    "AIProviderNotRegisteredError",
    "AIProviderPolicyError",
    "AIProviderRateLimitError",
    "AIProviderRegistry",
    "AIProviderTimeoutError",
    "AIProviderUnavailableError",
    "AIRequest",
    "AIResponse",
    "AIResponseFormat",
    "AIRouteAttempt",
    "AIRouteAttemptOutcome",
    "AIRoutedResponse",
    "AIRouter",
    "AIRoutingConfig",
    "AIRoutingConfigLoader",
    "AIRoutingError",
    "AIRoutingExecutionError",
    "AIRoutingMode",
    "AIRoutingPolicyError",
    "AITaskType",
    "LlamaCppProvider",
    "LlamaCppProviderConfig",
    "PromptReference",
    "ProviderCapabilities",
    "ProviderLocality",
    "TaskRoutingPolicy",
    "TokenUsage",
    "metadata_contains_secret_key",
    "require_provider_compatibility",
]
