"""publication_scheduler

Revision ID: 0010_publication_scheduler
Revises: 0009_human_review
Create Date: 2026-09-12 22:15:20.925194
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0010_publication_scheduler"
down_revision: str | Sequence[str] | None = "0009_human_review"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_assets",
        sa.Column("asset_type", sa.String(length=32), nullable=False),
        sa.Column("storage_provider", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("public_url", sa.Text(), nullable=True),
        sa.Column("mime_type", sa.String(length=128), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("visual_check_status", sa.String(length=32), nullable=True),
        sa.Column(
            "source_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(file_hash) = 64", name=op.f("ck_media_assets_media_file_hash")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_assets")),
    )
    op.create_table(
        "social_accounts",
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("account_name", sa.String(length=200), nullable=False),
        sa.Column("account_identifier", sa.String(length=256), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "PAUSED",
                "AUTH_ERROR",
                "RATE_LIMITED",
                "DISABLED",
                "REAUTH_REQUIRED",
                name="socialaccountstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("credential_reference", sa.String(length=256), nullable=True),
        sa.Column(
            "capabilities",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "rate_limit_state",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','PAUSED','AUTH_ERROR','RATE_LIMITED',"
            "'DISABLED','REAUTH_REQUIRED')",
            name=op.f("ck_social_accounts_account_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_social_accounts")),
        sa.UniqueConstraint(
            "platform", "account_identifier", name="uq_social_accounts_destination"
        ),
    )
    op.create_table(
        "publications",
        sa.Column("content_variant_id", sa.Uuid(), nullable=False),
        sa.Column("content_variant_version", sa.Integer(), nullable=False),
        sa.Column("content_draft_id", sa.Uuid(), nullable=False),
        sa.Column("fact_sheet_id", sa.Uuid(), nullable=False),
        sa.Column("fact_sheet_version", sa.Integer(), nullable=False),
        sa.Column("review_decision_id", sa.Uuid(), nullable=False),
        sa.Column("quality_check_id", sa.Uuid(), nullable=False),
        sa.Column("social_account_id", sa.Uuid(), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "READY_FOR_REVIEW",
                "APPROVED",
                "SCHEDULED",
                "PUBLISHING",
                "RETRYING",
                "BLOCKED",
                "PUBLISHED",
                "FAILED",
                "CANCELLED",
                name="publicationstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_actor_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("publish_now_idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("publish_now_request_hash", sa.String(length=64), nullable=True),
        sa.Column("publish_now_actor_id", sa.Uuid(), nullable=True),
        sa.Column("correlation_id", sa.Uuid(), nullable=True),
        sa.Column("scheduled_event_id", sa.Uuid(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancellation_reason", sa.String(length=2000), nullable=True),
        sa.Column("blocking_reason", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'CANCELLED') = (cancelled_at IS NOT NULL)",
            name=op.f("ck_publications_publication_cancelled"),
        ),
        sa.CheckConstraint(
            "status != 'SCHEDULED' OR scheduled_at IS NOT NULL",
            name=op.f("ck_publications_publication_schedule"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','READY_FOR_REVIEW','APPROVED','SCHEDULED',"
            "'PUBLISHING','RETRYING','BLOCKED','PUBLISHED','FAILED','CANCELLED')",
            name=op.f("ck_publications_publication_status"),
        ),
        sa.CheckConstraint(
            "content_variant_version >= 1 AND fact_sheet_version >= 1",
            name=op.f("ck_publications_publication_versions"),
        ),
        sa.CheckConstraint(
            "(publish_now_idempotency_key IS NULL AND publish_now_request_hash IS NULL "
            "AND publish_now_actor_id IS NULL) OR "
            "(publish_now_idempotency_key IS NOT NULL AND publish_now_request_hash IS NOT NULL "
            "AND publish_now_actor_id IS NOT NULL)",
            name=op.f("ck_publications_publication_publish_now_identity"),
        ),
        sa.CheckConstraint(
            "publish_now_request_hash IS NULL OR length(publish_now_request_hash) = 64",
            name=op.f("ck_publications_publication_publish_now_hash"),
        ),
        sa.ForeignKeyConstraint(
            ["content_draft_id"],
            ["content_drafts.id"],
            name=op.f("fk_publications_content_draft_id_content_drafts"),
        ),
        sa.ForeignKeyConstraint(
            ["content_variant_id"],
            ["content_variants.id"],
            name=op.f("fk_publications_content_variant_id_content_variants"),
        ),
        sa.ForeignKeyConstraint(
            ["fact_sheet_id"],
            ["fact_sheets.id"],
            name=op.f("fk_publications_fact_sheet_id_fact_sheets"),
        ),
        sa.ForeignKeyConstraint(
            ["quality_check_id"],
            ["content_quality_checks.id"],
            name=op.f("fk_publications_quality_check_id_content_quality_checks"),
        ),
        sa.ForeignKeyConstraint(
            ["review_decision_id"],
            ["review_decisions.id"],
            name=op.f("fk_publications_review_decision_id_review_decisions"),
        ),
        sa.ForeignKeyConstraint(
            ["scheduled_event_id"],
            ["event_outbox.event_id"],
            name=op.f("fk_publications_scheduled_event_id_event_outbox"),
        ),
        sa.ForeignKeyConstraint(
            ["social_account_id"],
            ["social_accounts.id"],
            name=op.f("fk_publications_social_account_id_social_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publications")),
        sa.UniqueConstraint(
            "created_by_actor_id", "idempotency_key", name="uq_publications_actor_operation"
        ),
        sa.UniqueConstraint("scheduled_event_id", name=op.f("uq_publications_scheduled_event_id")),
    )
    op.create_index(
        op.f("ix_publications_content_variant_id"),
        "publications",
        ["content_variant_id"],
        unique=False,
    )
    op.create_index("ix_publications_due", "publications", ["status", "scheduled_at"], unique=False)
    op.create_index(
        op.f("ix_publications_social_account_id"),
        "publications",
        ["social_account_id"],
        unique=False,
    )
    op.create_index(
        "uq_publications_active_candidate",
        "publications",
        ["content_variant_id", "content_variant_version", "social_account_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('DRAFT','APPROVED','SCHEDULED')"),
        sqlite_where=sa.text("status IN ('DRAFT','APPROVED','SCHEDULED')"),
    )
    op.alter_column("audit_log", "actor_id", existing_type=sa.UUID(), nullable=True)
    op.create_check_constraint(
        "audit_system_actor",
        "audit_log",
        "actor_id IS NOT NULL OR action IN ('PUBLICATION_SCHEDULED','PUBLICATION_BLOCKED')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint(op.f("ck_audit_log_audit_system_actor"), "audit_log", type_="check")
    op.execute(
        sa.text(
            "DELETE FROM audit_log WHERE actor_id IS NULL "
            "AND action IN ('PUBLICATION_SCHEDULED','PUBLICATION_BLOCKED')"
        )
    )
    op.alter_column("audit_log", "actor_id", existing_type=sa.UUID(), nullable=False)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_publications_active_candidate",
        table_name="publications",
        postgresql_where=sa.text("status IN ('DRAFT','APPROVED','SCHEDULED')"),
        sqlite_where=sa.text("status IN ('DRAFT','APPROVED','SCHEDULED')"),
    )
    op.drop_index(op.f("ix_publications_social_account_id"), table_name="publications")
    op.drop_index("ix_publications_due", table_name="publications")
    op.drop_index(op.f("ix_publications_content_variant_id"), table_name="publications")
    op.drop_table("publications")
    op.drop_table("social_accounts")
    op.drop_table("media_assets")
    # ### end Alembic commands ###
